/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { GridProps, TextFieldProps } from "@aws-amplify/ui-react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { Adline } from "../models";
export declare type ValidationResponse = {
    hasError: boolean;
    errorMessage?: string;
};
export declare type ValidationFunction<T> = (value: T, validationResponse: ValidationResponse) => ValidationResponse | Promise<ValidationResponse>;
export declare type AdlineUpdateFormInputValues = {
    dim_ad_id?: string;
    ad_name?: string;
    ad_cfid?: string;
    ad_url?: string;
    ad_status?: string;
    ms_ss?: string;
    line_item_type?: string;
    sales_vertical?: string;
    advertiser_vertical?: string;
    advertiser_cfid?: string;
    advertiser_name?: string;
    service_type?: string;
    advertiser_industry?: string;
    advertiser_sub_industry?: string;
    campaign_cfid?: string;
    campaign_name?: string;
    campaign_goal?: string;
    campaign_goal_category?: string;
    is_supply_3px?: number;
    is_supply_ono?: number;
    is_supply_aps?: number;
    is_endemic?: number;
    is_onsite?: number;
    is_offsite?: number;
    base_bid?: number;
    dim_date?: string;
    impressions?: number;
    spend?: number;
    clicks?: number;
    m2_considerations_click?: number;
    purchases?: number;
    purchase_amounts?: number;
    avg_max_bid?: number;
    number_bid_request_eligible?: number;
    number_bid_request_won_in_cs?: number;
    number_impressions?: number;
    total_impression_at_max_bid?: number;
    internal_win_rate?: number;
    external_win_rate?: number;
    average_bidamount_among_bids?: number;
};
export declare type AdlineUpdateFormValidationValues = {
    dim_ad_id?: ValidationFunction<string>;
    ad_name?: ValidationFunction<string>;
    ad_cfid?: ValidationFunction<string>;
    ad_url?: ValidationFunction<string>;
    ad_status?: ValidationFunction<string>;
    ms_ss?: ValidationFunction<string>;
    line_item_type?: ValidationFunction<string>;
    sales_vertical?: ValidationFunction<string>;
    advertiser_vertical?: ValidationFunction<string>;
    advertiser_cfid?: ValidationFunction<string>;
    advertiser_name?: ValidationFunction<string>;
    service_type?: ValidationFunction<string>;
    advertiser_industry?: ValidationFunction<string>;
    advertiser_sub_industry?: ValidationFunction<string>;
    campaign_cfid?: ValidationFunction<string>;
    campaign_name?: ValidationFunction<string>;
    campaign_goal?: ValidationFunction<string>;
    campaign_goal_category?: ValidationFunction<string>;
    is_supply_3px?: ValidationFunction<number>;
    is_supply_ono?: ValidationFunction<number>;
    is_supply_aps?: ValidationFunction<number>;
    is_endemic?: ValidationFunction<number>;
    is_onsite?: ValidationFunction<number>;
    is_offsite?: ValidationFunction<number>;
    base_bid?: ValidationFunction<number>;
    dim_date?: ValidationFunction<string>;
    impressions?: ValidationFunction<number>;
    spend?: ValidationFunction<number>;
    clicks?: ValidationFunction<number>;
    m2_considerations_click?: ValidationFunction<number>;
    purchases?: ValidationFunction<number>;
    purchase_amounts?: ValidationFunction<number>;
    avg_max_bid?: ValidationFunction<number>;
    number_bid_request_eligible?: ValidationFunction<number>;
    number_bid_request_won_in_cs?: ValidationFunction<number>;
    number_impressions?: ValidationFunction<number>;
    total_impression_at_max_bid?: ValidationFunction<number>;
    internal_win_rate?: ValidationFunction<number>;
    external_win_rate?: ValidationFunction<number>;
    average_bidamount_among_bids?: ValidationFunction<number>;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type AdlineUpdateFormOverridesProps = {
    AdlineUpdateFormGrid?: PrimitiveOverrideProps<GridProps>;
    dim_ad_id?: PrimitiveOverrideProps<TextFieldProps>;
    ad_name?: PrimitiveOverrideProps<TextFieldProps>;
    ad_cfid?: PrimitiveOverrideProps<TextFieldProps>;
    ad_url?: PrimitiveOverrideProps<TextFieldProps>;
    ad_status?: PrimitiveOverrideProps<TextFieldProps>;
    ms_ss?: PrimitiveOverrideProps<TextFieldProps>;
    line_item_type?: PrimitiveOverrideProps<TextFieldProps>;
    sales_vertical?: PrimitiveOverrideProps<TextFieldProps>;
    advertiser_vertical?: PrimitiveOverrideProps<TextFieldProps>;
    advertiser_cfid?: PrimitiveOverrideProps<TextFieldProps>;
    advertiser_name?: PrimitiveOverrideProps<TextFieldProps>;
    service_type?: PrimitiveOverrideProps<TextFieldProps>;
    advertiser_industry?: PrimitiveOverrideProps<TextFieldProps>;
    advertiser_sub_industry?: PrimitiveOverrideProps<TextFieldProps>;
    campaign_cfid?: PrimitiveOverrideProps<TextFieldProps>;
    campaign_name?: PrimitiveOverrideProps<TextFieldProps>;
    campaign_goal?: PrimitiveOverrideProps<TextFieldProps>;
    campaign_goal_category?: PrimitiveOverrideProps<TextFieldProps>;
    is_supply_3px?: PrimitiveOverrideProps<TextFieldProps>;
    is_supply_ono?: PrimitiveOverrideProps<TextFieldProps>;
    is_supply_aps?: PrimitiveOverrideProps<TextFieldProps>;
    is_endemic?: PrimitiveOverrideProps<TextFieldProps>;
    is_onsite?: PrimitiveOverrideProps<TextFieldProps>;
    is_offsite?: PrimitiveOverrideProps<TextFieldProps>;
    base_bid?: PrimitiveOverrideProps<TextFieldProps>;
    dim_date?: PrimitiveOverrideProps<TextFieldProps>;
    impressions?: PrimitiveOverrideProps<TextFieldProps>;
    spend?: PrimitiveOverrideProps<TextFieldProps>;
    clicks?: PrimitiveOverrideProps<TextFieldProps>;
    m2_considerations_click?: PrimitiveOverrideProps<TextFieldProps>;
    purchases?: PrimitiveOverrideProps<TextFieldProps>;
    purchase_amounts?: PrimitiveOverrideProps<TextFieldProps>;
    avg_max_bid?: PrimitiveOverrideProps<TextFieldProps>;
    number_bid_request_eligible?: PrimitiveOverrideProps<TextFieldProps>;
    number_bid_request_won_in_cs?: PrimitiveOverrideProps<TextFieldProps>;
    number_impressions?: PrimitiveOverrideProps<TextFieldProps>;
    total_impression_at_max_bid?: PrimitiveOverrideProps<TextFieldProps>;
    internal_win_rate?: PrimitiveOverrideProps<TextFieldProps>;
    external_win_rate?: PrimitiveOverrideProps<TextFieldProps>;
    average_bidamount_among_bids?: PrimitiveOverrideProps<TextFieldProps>;
} & EscapeHatchProps;
export declare type AdlineUpdateFormProps = React.PropsWithChildren<{
    overrides?: AdlineUpdateFormOverridesProps | undefined | null;
} & {
    id?: string;
    adline?: Adline;
    onSubmit?: (fields: AdlineUpdateFormInputValues) => AdlineUpdateFormInputValues;
    onSuccess?: (fields: AdlineUpdateFormInputValues) => void;
    onError?: (fields: AdlineUpdateFormInputValues, errorMessage: string) => void;
    onChange?: (fields: AdlineUpdateFormInputValues) => AdlineUpdateFormInputValues;
    onValidate?: AdlineUpdateFormValidationValues;
} & React.CSSProperties>;
export default function AdlineUpdateForm(props: AdlineUpdateFormProps): React.ReactElement;
